# Generated by Django 5.2.4 on 2025-07-04 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("WORKING", "Working"),
                            ("REMOTE", "Working Remotely"),
                            ("VACATION", "On Vacation"),
                            ("BUSINESS_TRIP", "Business Trip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Status",
                "verbose_name_plural": "Employee Statuses",
                "ordering": ["-updated_at"],
            },
        ),
    ]
